# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2jJmyb2ENY3fF48ZsQAZ8aSXlux8iKI
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Set konfigurasi halaman web
st.set_page_config(page_title="Bitcoin Market Regime", page_icon="📊", layout="centered")

# ==========================================
# 1. MEMUAT ARTIFACT MODEL & SCALER
# ==========================================
@st.cache_resource
def load_model_artifacts():
    # Menggunakan cache_resource agar model tidak di-load berulang-ulang setiap web di-refresh
    kmeans = joblib.load('model_kmeans.pkl')
    scaler = joblib.load('scaler.pkl')
    return kmeans, scaler

try:
    kmeans, scaler = load_model_artifacts()
except Exception as e:
    st.error(f"Gagal memuat file model. Pastikan file 'kmeans_bitcoin.pkl' dan 'scaler_bitcoin.pkl' sudah diunggah di folder yang sama. Error: {e}")
    st.stop()

# ==========================================
# 2. ANTARMUKA PENGGUNA (UI STREAMLIT)
# ==========================================
st.title("📊 Aplikasi Deteksi Kondisi Pasar Bitcoin")
st.write("Masukkan parameter perdagangan harian di bawah ini untuk mengidentifikasi fase psikologi pasar (*Market Regimes*) menggunakan algoritma **K-Means Clustering**.")

st.markdown("---")
st.subheader("📥 Input Data Perdagangan Harian")

# Membagi input menjadi 2 kolom agar tampilan lebih rapi
col1, col2 = st.columns(2)

with col1:
    open_price = st.number_input("Harga Open Hari Ini (USD)", value=40000.0, step=100.0)
    high_price = st.number_input("Harga High Hari Ini (USD)", value=42000.0, step=100.0)
    low_price = st.number_input("Harga Low Hari Ini (USD)", value=39000.0, step=100.0)
    close_price = st.number_input("Harga Close Hari Ini (USD)", value=41500.0, step=100.0)

with col2:
    close_kemarin = st.number_input("Harga Close KEMARIN (USD)", value=39000.0, step=100.0)
    sma_7 = st.number_input("Rata-rata Harga 7 Hari Terakhir (SMA 7)", value=39500.0, step=100.0)
    volume = st.number_input("Volume Transaksi Hari Ini", value=50000000000.0, step=1000000.0)

st.markdown("---")

# ==========================================
# 3. PROSES PREDIKSI & OUTPUT KEPUTUSAN
# ==========================================
if st.button("🚀 Analisis Kondisi Pasar", use_container_width=True):
    # Melakukan Feature Engineering secara Real-Time (On-the-Fly)
    daily_return = (close_price - close_kemarin) / close_kemarin
    volatility = (high_price - low_price) / open_price
    price_to_sma7 = close_price / sma_7

    # Menyusun ke dalam format DataFrame yang sesuai saat training
    input_data = pd.DataFrame([[daily_return, volatility, price_to_sma7, volume]],
                              columns=['Daily_Return', 'Volatility', 'Price_to_SMA7', 'Volume'])

    # Standarisasi data menggunakan scaler yang sudah dilatih
    input_scaled = scaler.transform(input_data)

    # Prediksi nomor cluster
    cluster = kmeans.predict(input_scaled)[0]

    # Menampilkan hasil interpretasi bisnis berdasarkan nomor cluster
    st.subheader(f"Hasil Analisis: **Cluster {cluster}**")

    if cluster == 0:
        st.success("### **FASE BULLISH EKSTREM** 📈")
        st.write("**Karakteristik:** Tingkat keuntungan harian (*return*) sangat tinggi, volatilitas tinggi, dan harga bergerak jauh di atas tren mingguan. Ini menandakan pasar sedang mengalami tren naik yang sangat kuat (*rally*).")
    elif cluster == 1:
        st.error("### **FASE BEARISH / KOREKSI TAJAM** 📉")
        st.write("**Karakteristik:** Terjadi penurunan harga yang signifikan (*return* negatif), fluktuasi harga sangat liar, dan harga berada di bawah tren mingguan. Sinyal kuat adanya kepanikan pasar (*panic selling*) atau *crash*.")
    elif cluster == 2:
        st.info("### **FASE SIDEWAYS KLASIK (Era Lama)** ⏳")
        st.write("**Karakteristik:** Harga cenderung stabil mendatar (*return* mendekati 0), tingkat volatilitas sangat rendah, dan volume transaksi kecil. Biasanya mencerminkan kondisi pasar Bitcoin di tahun-tahun awal perkembangannya.")
    elif cluster == 3:
        st.warning("### **FASE SIDEWAYS MODERN / KONSOLIDASI** 🔄")
        st.write("**Karakteristik:** Harga bergerak stabil dalam rentang tertentu (*sideways*), namun didukung oleh volume transaksi harian yang sangat raksasa. Menunjukkan fase akumulasi pasar di era modern.")